---
  - name: restart tmpfiles
    become: True
    command: systemd-tmpfiles --create

  - name: restart haproxy
    become: True
    service: name=haproxy state=restarted enabled=yes

  - name: reload systemd
    become: True
    command: systemctl daemon-reload
